### ISSUE TITLE
Add a way to scrub the environment

### ISSUE THREAD

**Issue by madaidan** [GrapheneOS/hardened_malloc#101]
I want to use apparmor's environment scrubbing to execute a program and also use it with hardened_malloc. I can't use hardened_malloc system-wide (too much breakage) so I need to configure specific programs to use it with LD_PRELOAD.

As apparmor's environment scrubbing clears LD_PRELOAD, this won't work. I created an issue on the gitlab repo and got this response:

> The good news is that you could steal the environment scrubbing routine
from glibc, add it as a constructor to your libhardened_malloc.so, and
modify AppArmor policy to stop setting the secure exec flag when you want
to use this library. That way you could still get a mostly-scrubbed
environment and use the different allocator. It might not be as easy as
this fine-grained scrubbing feature but you could be using it a lot sooner.

https://gitlab.com/apparmor/apparmor/issues/66

Would it be possible to implement this in hardened_malloc?

Background: https://forums.whonix.org/t/apparmor-for-complete-system-including-init-pid1-systemd-everything-full-system-mac-policy/8339/156

**Comment by thestinger** [comment]
I'd recommend just linking those programs against it. I don't want to add this.
