### ISSUE TITLE
Compilation error on Alpine/musl-libc (missing-prototypes)

### ISSUE THREAD

**Issue by ShadyRoach** [GrapheneOS/hardened_malloc#104]
Hi, I'm trying to build this project on the following setup:
Alpine: 3.11.3
gcc: 9.2.0
musl-libc: 1.1.24
hardened_malloc: QQ1A.200105.002.2020.01.06.21

Running `make` results in following error:

> In file included from h_malloc.c:25:
> 
> h_malloc.h:32:28: error: no previous prototype for 'malloc_get_state' [-Werror=missing-prototypes]
> 32 | #define h_malloc_get_state malloc_get_state
> 
> h_malloc.c:1826:19: note: in expansion of macro 'h_malloc_get_state'
> 1826 | COLD EXPORT void *h_malloc_get_state(void) {
> 
> h_malloc.h:33:28: error: no previous prototype for 'malloc_set_state' [-Werror=missing-prototypes]
> 33 | #define h_malloc_set_state malloc_set_state
> 
> h_malloc.c:1830:17: note: in expansion of macro 'h_malloc_set_state'
> 1830 | COLD EXPORT int h_malloc_set_state(UNUSED void *state) {

As this malloc implementation is said to work with musl, it means that either my setup is wrong or that there is a bug within line 32 and 33 of h_malloc.h, right? Either way, I'm seeking some assistance please.

**Comment by thestinger** [comment]
It's a warning, not a bug.

**Comment by thestinger** [comment]
You're free to build with `CONFIG_WERROR` set to `false` if you don't want to address unexpected warnings. The default is to block building since it's important to consider new warnings with new compiler versions, environments that aren't tested to the same extent, etc.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/hardened_malloc/commit/449962e04403702f14a3c4829aa36d3f1f0a79a7
