### ISSUE TITLE
Clarification on Usefulness with Browsers and Other applications

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/hardened_malloc#108]
Sorry to distract from the technical issues, however I find that there is some uncertainty as to whether desktop users should use hardened_malloc in conjunction with browsers and other apps.

Firefox uses jemalloc and I think is pluggable in that alternatives can be supplied, but even default builds are going to use malloc behind the scenes as part of jemalloc...so is using hardened_malloc here a valid use case or not?

The whonix wiki implies not...other places I have looked seem to give no indication either way:
https://www.whonix.org/wiki/Hardened_Malloc

Thanks again for GrapheneOS and hardened_malloc both!

**Comment by thestinger** [comment]
It's meant to be used globally as a replacement for the malloc implementation in libc. Some applications do have their own allocators but in many cases they can be disabled.
