### ISSUE TITLE
Comparison to Scudo

### ISSUE THREAD

**Issue by milkey-mouse** [GrapheneOS/hardened_malloc#112]
How does this allocator compare to the [Scudo](https://llvm.org/docs/ScudoHardenedAllocator.html) allocator that will [become Android 11's default](https://security.googleblog.com/2020/06/system-hardening-in-android-11.html)? Does this still offer a substantial improvement or make different tradeoffs?

**Comment by thestinger** [comment]
I think https://github.com/GrapheneOS/hardened_malloc/blob/master/README.md already covers it well. Scudo is a traditional allocator design with inline metadata and weak probabilistic metadata protection. I don't consider it to be hardened in the same sense as hardened_malloc. It's a lot closer to what you get if you keep bolting on security features to a traditional allocator design.
