### ISSUE TITLE
Should h_free() call enforce_init()?

### ISSUE THREAD

**Issue by cyanlemons** [GrapheneOS/hardened_malloc#124]
Upon doing some more digging for #123 ([my findings](https://bugzilla.mozilla.org/show_bug.cgi?id=1668674#c3) if you are interested), I have realized `h_free()` does not immediately call `enforce_init()` and I wonder if it should.

Here is a trimmed excerpt from `h_malloc_usable_size()`:
```c
size_t h_malloc_usable_size(void *p) {
    if (p == NULL) {
        return 0;
    }

    enforce_init();

    if (p >= get_slab_region_start() && p < ro.slab_region_end) { /* ... */ }
    /* ... */
}
```

However, essentially this same snippet of code occurs in `h_free()` (and `h_free_sized()` for that matter) with a read to `get_slab_region_start()`, except without the call to `enforce_init()`.

As `get_slab_region_start()` may be `NULL` when read in the aforementioned free functions, would it not be prudent and consistent to call `enforce_init()` before doing so, just like in `malloc_usable_size()`?

**Comment by thestinger** [comment]
It doesn't call it as an optimization since it will fall through to `deallocate_large` which does call it. The `p >= get_slab_region_start()` call will always be false if it's not initialized.

**Comment by cyanlemons** [comment]
@thestinger I don't believe that is correct. `NULL` is equivalent to `0` when doing comparisons. Here's a [godbolt demo](https://godbolt.org/z/559P6r) showing that the same comparison to always be true, not false.

**Comment by thestinger** [comment]
I was explaining it wrong. I mean that `p < ro.slab_region_end` will always be false.

**Comment by thestinger** [comment]
> I don't believe that is correct. NULL is equivalent to 0 when doing comparisons

I'm well aware of the basics of C. I think you can figure out what I meant about the overall comparison.

**Comment by thestinger** [comment]
If it's not initialized, it falls through to the code for large deallocations, and will not find the pointer in the hash table, which is detected as an error.

**Comment by thestinger** [comment]
If it's not initialized, it falls through to the code for large deallocations, and will not find the pointer in the hash table, which is detected as an error. There is a test case for this which shows that it works properly. You need to disable the early initialization constructor to actually trigger it.

**Comment by cyanlemons** [comment]
It seemed like a reasonable interpretation given the fact that you only quoted the first half of the if statement `p >= get_slab_region_start()`. It wasn't meant as an insult, it's just there was some inherent ambiguity there.

In any case, I now see what you mean in regards to the fall through to `deallocate_large()`.

**Comment by thestinger** [comment]
I made a mistake and didn't copy the whole expression into the inline code block.

**Comment by thestinger** [comment]
Since you got me to look over this code, I decided to make an improvement to this sanity check:

https://github.com/GrapheneOS/hardened_malloc/commit/178d4f320f0a0798d066fec12c196963a7ee608c

It's not going to impact whatever you're running into this.

**Comment by thestinger** [comment]
I ended up making an improvement to this sanity check after looking over the code:

https://github.com/GrapheneOS/hardened_malloc/commit/178d4f320f0a0798d066fec12c196963a7ee608c

It's not going to impact whatever is causing the problem you're encountering. The previous way of doing this didn't make sense though since it's `p < slab_region_end` which is never true before initialization, so that check is what should be done first.

**Comment by thestinger** [comment]
To clarify something though: a non-hardened implementation would not perform these `enforce_init` or equivalent checks at all, and would just fall through to more complex failure cases. The point of this is to catch undefined behavior by the application as early as possible to produce a clear error rather than having more complex / messy failure cases for this.
