### ISSUE TITLE
Interesting mlockall() / pthread_create() interplay

### ISSUE THREAD

**Issue by snicket2100** [GrapheneOS/hardened_malloc#128]
I have discovered this issue when trying to run `chronyd` with `hardened_malloc`.

The `chronyd` deamon does:
```
mlockall(MCL_CURRENT|MCL_FUTURE)
```
on startup, then when it tries to start a new thread with `pthread_create`, thread stack allocation fails with:
```
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 EAGAIN (Resource temporarily unavailable)
```
which is clearly related to `mlockall()`, both according to the `mmap` manpage which says:
```
ERRORS
       The mmap() function shall fail if:

       EACCES The fildes argument is not open for read, regardless of the protection specified, or fildes is not open for write and PROT_WRITE was specified for a MAP_SHARED type mapping.

       EAGAIN The mapping could not be locked in memory, if required by mlockall(), due to a lack of resources.
[...]
```
as well as I checked that commenting out the `mlockall()` call makes it work fine.

**Comment by snicket2100** [comment]
This is the `pthread_create` call that fails: https://github.com/mlichvar/chrony/blob/master/nameserv_async.c#L119.

This is the `mlockall()` call that makes it work fine again when removed: https://github.com/mlichvar/chrony/blob/master/sys_posix.c#L103.

**Comment by thestinger** [comment]
The Linux kernel may have the deficiency of applying `mlockall` to unused `PROT_NONE` mappings even though they aren't accountable memory. You'll need to report this as a problem in the Linux kernel. There's nothing that hardened_malloc and other programs heavily using PROT_NONE mappings can do about flaws in the Linux kernel implementation.

Try passing `MCL_ONFAULT` as an additional flag to `mlockall`. You could suggest that to the chrony developers to work around the flawed kernel implementation. `mlockall` definitely shouldn't apply to unused `PROT_NONE` mappings. Other OSes even have documentation promising that it won't.

**Comment by thestinger** [comment]
This has been reported upstream at https://lore.kernel.org/linux-mm/70885d37-62b7-748b-29df-9e94f3291736@gmail.com/. Hopefully, this can be easily fixed in the Linux kernel.
