### ISSUE TITLE
`fatal allocator error: sized deallocation mismatch (large)` when running node as root.

### ISSUE THREAD

**Issue by kayabaNerve** [GrapheneOS/hardened_malloc#129]
Happens on Arch Linux, specifically when importing a module. Requiring a system module such as fs is fine, yet importing anything from NPM causes this.

I wasn't sure if this is a faulty check in hardened_malloc (as #126 did cause changes within hardened_malloc) or a fault in node itself.

Specifically on Erbium LTS (v12.20.1), believed to be a fault with https://github.com/nodejs/node/blob/v12.20.1/src/node_file.cc#L870. That said, Fermium (the latest LTS, v14) works without issue. Because of that, I assume this will be closed due to hardened_malloc working as intended. Just wanted to offer the heads up.

I am also running Linux hardened if that matters.

**Comment by thestinger** [comment]
The check in `hardened_malloc` should be fine now. Since this is fixed in the latest release, it was probably a bug they found and fixed with a tool like ASan with a similar check. Maybe you can find the fix and ask them to backport it. This occurs because of an issue like a mismatched type for a `new` and `delete` call.

**Comment by kayabaNerve** [comment]
Yep. I did assume it was h_m working as it should when I saw the newer version was fine. Just wanted to double check because of 126 being rather recent in case there was more to it. Thanks for confirming :)

**Comment by kayabaNerve** [comment]
Correction I only just realized: does not work even under latest node. No idea if that changes the likelihood the hardened_malloc check is still off.

**Comment by thestinger** [comment]
You should see if you can get it built with ASan which should discover the same issue.

**Comment by thestinger** [comment]
Also, better to report an issue to them with ASan (which they have heard of and which is a debugging tool providing detailed debugging output including tracebacks of allocation site and free site) than hardened_malloc.

**Comment by kayabaNerve** [comment]
Will do, thanks.

**Comment by PlasmaPower** [comment]
From my debugging, this seems to be a hardened_malloc bug. Here's it having just allocated the memory at 0x72fd94fa2000 with size 0x20000:
```
   1313	     unsigned arena = init();
   1314	     thread_unseal_metadata();
   1315	     size = adjust_size_for_canaries(size);
   1316	     void *p = allocate(arena, size);
   1317	     thread_seal_metadata();
 → 1318	     return p;
   1319	 }
   1320	
   1321	 EXPORT void *h_malloc(size_t size) {
   1322	     return alloc(size);
   1323	 }

[#0] 0x7f7db4f388dd → alloc(size=0x20008)
[#1] 0x7f7db4f388fb → malloc(size=0x20000)
[#2] 0x7f7db4f3a9bf → new_impl(size=0x20000, nothrow=0x0)
[#3] 0x7f7db4f3aa0a → operator new(size=0x20000)
[#4] 0x55ced49a9563 → std::vector<char, std::allocator<char> >::_M_default_append(unsigned long)()
[#5] 0x55ced49a4668 → node::fs::InternalModuleReadJSON(v8::FunctionCallbackInfo<v8::Value> const&)()
[#6] 0x55ced4c0b9af → v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo)()
[#7] 0x55ced4c0c740 → v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)()
[#8] 0x55ced4c0cc4a → v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*)()
[#9] 0x55ced4c0ced6 → v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*)()

gef➤  print p
$1 = (void *) 0x72fd94fa2000
```

Note there is some weirdness in the size parameter there, it's 0x20000 from operator new all the way down to the alloc call where it turns to 0x20008. I'm assuming that's some sort of internal thing to hardened_malloc.

And here's it attempting to free the same memory with the same size, yet calling fatal_error:
```
[#0] 0x7f7db49f1615 → raise()
[#1] 0x7f7db49da862 → abort()
[#2] 0x7f7db4f3a911 → fatal_error(s=0x7f7db4f3b830 "sized deallocation mismatch (large)")
[#3] 0x7f7db4f385f0 → deallocate_large(p=0x72fd94fa2000, expected_size=0x7ffeb4457ba0)
[#4] 0x7f7db4f39247 → free_sized(p=0x72fd94fa2000, expected_size=0x20000)
[#5] 0x7f7db4f3ab09 → operator delete(ptr=0x72fd94fa2000, size=0x20000)
[#6] 0x55ced49a4952 → node::fs::InternalModuleReadJSON(v8::FunctionCallbackInfo<v8::Value> const&)()
[#7] 0x55ced4c0b9af → v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo)()
[#8] 0x55ced4c0c740 → v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)()
[#9] 0x55ced4c0cc4a → v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*)()
```

I traced this down by using reverse debugging and doing a reverse continue with a conditional breakpoint on the alloc return checking the returned pointer. I also confirmed there's no realloc calls between the alloc and the free.

**Comment by thestinger** [comment]
Are you using the latest release?

**Comment by thestinger** [comment]
Can you build hardened_malloc with the slab canary feature disabled? There's a special case that's probably not be handled properly for the boundary between small and large allocations.

**Comment by PlasmaPower** [comment]
I built this from master (with debugging symbols). @kayabaNerve is using the latest release I believe. Disabling slab canary in the makefile (then removing *.o so it actually rebuilds) does fix this.

**Comment by PlasmaPower** [comment]
MRE:
```c++
struct Example {
  unsigned char data[0x20000];
};

int main() {
  Example *foo = new Example;
  delete foo;
  return 0;
}
```

**Comment by thestinger** [comment]
Yes it's similar to the last issue. It's an interaction between slab canaries and the C++ sized deallocation check which is still experimental.

**Comment by thestinger** [comment]
For an actual production workaround, disable the C++ allocator option rather than slab canaries. The C++ sized allocation check is a bonus feature that's not very mature and may have these kinds of issues in certain configurations since it's trying to enforce something subtle in a strict way where we need to fix all the false positives for it to work properly. Hopefully, this is the last of the false positives.

**Comment by thestinger** [comment]
Please try https://github.com/GrapheneOS/hardened_malloc/commit/52755632528d819147985bfe15a11849287f1634. I'll make another release once it has been tested.

**Comment by PlasmaPower** [comment]
Yep, that commit fixes both node and my MRE on my system (with slab canaries re-enabled of course).
