### ISSUE TITLE
add test utility to check whether hardened malloc is in use or not

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#134]
Loading hardened malloc using `/etc/ld.so.preload`. But it's not easy to know if that is functional in all environments (such as daemons started by systemd or inside chroot).

To check if hardened malloc is in use or not it would be useful to have a simple command line utility. Could you please add such a utility? (Exit code zero vs non-zero.)

Otherwise, is there some other easy way to detect if hardened malloc is in use or not?

**Comment by thestinger** [comment]
You can determine that via `/proc/$PID/maps` by either looking for the dynamically loaded library or looking at the memory layout. You could do that generically for any library that's forced loaded this way. I would suggest just using `grep /full/path/to/library.so /proc/$PID/maps`. I think that provides what you want without us needing to make a script.

Ideally, it's included in libc as the standard allocator. That's the approach we take to deploying it as part of GrapheneOS. It could also be linked against specific applications to use it for those. It's nicest to have it in libc though.

I don't really want to emphasize a focus on what I don't really consider a production way to deploy it. The `preload.sh` script is included for development usage.

**Comment by thestinger** [comment]
It also has support for labelling the memory mappings it makes so they appear as `anon:name it assigns to them` but that requires an out-of-tree Linux kernel patch. It's one of the optional Android kernel patches (no longer has any mandatory downstream patches) included in the Android common kernels and kernels based on those.
