### ISSUE TITLE
h_malloc.c:115:21: error: unused variable 'min_extended_size_class' [-Werror,-Wunused-const-variable] static const size_t min_extended_size_class = 20480;

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#135]
Since https://github.com/GrapheneOS/hardened_malloc/releases/tag/7

> h_malloc.c:115:21: error: unused variable 'min_extended_size_class' [-Werror,-Wunused-const-variable]
static const size_t min_extended_size_class = 20480;

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/hardened_malloc/commit/39526453181babac2ba2ef3d09a406f2b7ff0305
