### ISSUE TITLE
Debian 11 `bullseye` `arm64` - clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#149]
Debian 11 `bullseye` `arm64` issue:

> clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]

Not happening for `amd64`.

**Comment by Zanthed** [comment]
Can't reproduce this on RPi 4B running aarch64 Debian 11.
What's the output of `clang -v`?

**Comment by adrelanos** [comment]
clang -v

```
Debian clang version 11.0.1-2
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/10
Selected GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by thestinger** [comment]
That error is correct since Clang 11 doesn't have an implementation of -fstack-clash-protection for arm64. The warning will go away once an implementation ships.

**Comment by thestinger** [comment]
I would have thought that our `safe_flag` check deals with this already.

**Comment by thestinger** [comment]
We only pass -fstack-clash-protection when the compiler is detected as supporting it.

**Comment by thestinger** [comment]
I don't see how this could happen unless the Makefile was changed.

**Comment by Zanthed** [comment]
This is still an issue. Attempting to compile on macOS arm64 throws this error.

https://github.com/GrapheneOS/hardened_malloc/issues/183#issuecomment-1010386581
https://github.com/GrapheneOS/hardened_malloc/issues/183#issuecomment-1010387993

Someone needs to take a look at the Makefile definition lines regarding it: https://github.com/GrapheneOS/hardened_malloc/blob/main/Makefile#L16-L18
