### ISSUE TITLE
[Question/Linux] Exclude programs from golbal setting in ld.so.preload.

### ISSUE THREAD

**Issue by s-a-p-i-e-n-s** [GrapheneOS/hardened_malloc#152]
Hi there,

this is not a technical but a usability question.
```
[sapiens@computer ~]$ cat /etc/ld.so.preload 
/usr/lib/libhardened_malloc.so
```
As you can see I have made hardened_malloc the global default. I am however now facing a problem that certain programs crash when using it, one reproduceable example is [Handbrake](https://handbrake.fr/).

Is there a way to set hardened_malloc as a global default while exclude certain programs from using it? I was unable to find a answer to this question anywhere.

Thanks in advance and have a great day everyone!

**Comment by Zanthed** [comment]
You should use a container or namespace without hardened_malloc in the container/namespace to make exceptions.

**Comment by thestinger** [comment]
I don't really see a reasonable way for hardened_malloc to offer anything for this.

**Comment by thestinger** [comment]
You can use mount namespaces to replace that file or you could use the LD_PRELOAD approach but it's really meant to be used globally.
