### ISSUE TITLE
make clean does not delete pycache in test folder

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#185]
Could you please delete `test/simple-memory-corruption/__pycache__/*` too? Example: `test/simple-memory-corruption/__pycache__/__init__.cpython-39.pyc`

**Comment by jvoisin** [comment]
I think that this issue is python-specific: I don't have those folders locally on my machine after running the testsuite.
You can get rid of them with a `git clean -xdf`.

**Comment by adrelanos** [comment]
I am on Debian stable which is pretty widespread. I guess this is a pretty much common python thing.

Would still be better if `make clean` would delete these files as these are troublesome for packagers since packaging policy suggests to not ship compiled (`.pyc`) files in upstream tarball.
