### ISSUE TITLE
Integrate into AOSP

### ISSUE THREAD

**Issue by CaseyBakey** [GrapheneOS/hardened_malloc#194]
Hello there,

I'm trying to integrate hardened_malloc into AOSP 12.

I did read your README.md, and use your integration code, but used the "updated" version aka commit e63d04c named "use Scudo on 32-bit and hardened_malloc on 64-bit".

The patch applied just fine.

I also git clone hardened_malloc under aosp_folder/external/hardened_malloc

But at build time, I got the following error:

"
error: bionic/apex/Android.bp:32:1: module "com.android.runtime" variant "android_common_com.android.runtime_image": "libc" requires "libhardened_malloc" that doesn't list the APEX ander 'apex_available'.
"

I did check other commits in your Bionic fork, but it doesn't seem to need other changes to integrate hardened_malloc.

Do you have an idea of where lays the problem?

**Comment by thestinger** [comment]
You need a soong change too.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_build_soong/commit/cc973e807d440a2cfe7bed420fbf7ae25985ddc1
