### ISSUE TITLE
ping throws a weird error when used with light config

### ISSUE THREAD

**Issue by Zanthed** [GrapheneOS/hardened_malloc#196]
```
# LD_PRELOAD=libhardened_malloc-light.so /bin/ping
ERROR: ld.so: object 'libhardened_malloc-light.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/bin/ping: usage error: Destination address required
```

Using normal config doesn't have this issue.

```
# LD_PRELOAD=libhardened_malloc.so /bin/ping
/bin/ping: usage error: Destination address required
```

Reported by @Wonderfall

**Comment by thestinger** [comment]
You should pass the full path for LD_PRELOAD.

**Comment by Zanthed** [comment]
I believe they said the issue happens even if the full path is in their ld.so.preload file.

**Comment by Wonderfall** [comment]
Yeah, happens with the full path for me.

`cat /etc/ld.so.preaload` :
```
/usr/local/lib/libhardened_malloc-light.so
```

It can see it being preloaded with `ldd`, and I couldn't find any other binary with that behavior at the moment. I'm trying other things to see if I can narrow down the issue.

**Comment by thestinger** [comment]
It's probably because it's a setuid or setcap binary instead of the more modern approach not requiring it.

**Comment by Wonderfall** [comment]
It's a fresh Arch install and doesn't seem to be setuid/setgid: 

```
-rwxr-xr-x 1 root root    76568 Dec 22 11:10  ping
```

**Comment by Wonderfall** [comment]
I suspect it's the default AppArmor profile for `ping`. I'm going to study the profile in question to confirm.

**Comment by thestinger** [comment]
Check if it's setcap (CAP_NET_RAW). There's another way to do it but setcap would break this too.

**Comment by Wonderfall** [comment]
I can confirm it was the default AppArmor profile. Sorry for causing trouble. Most likely because the default profile which includes the [base restrictions](https://gitlab.com/apparmor/apparmor/-/blob/master/profiles/apparmor.d/abstractions/base#L64) expect `/etc` to read-only.
