### ISSUE TITLE
malloc(0) should allow over-fetching

### ISSUE THREAD

**Issue by jreiser** [GrapheneOS/hardened_malloc#204]
`malloc(0)` currently returns a pointer into a page that has no Read and no Write access.  Instead, the page should allow Read, so that a program can "over-fetch" without triggering SIGSEGV.  Of course it is a logical error to *use* any of the fetched bytes, but delaying the effective check for logically-permitted access (such as by checking independently for length of zero) can be useful to increase speed by overlapping the check with the fetch.

**Comment by thestinger** [comment]
I don't see a reason to permit read access. It's undefined behavior to read the memory.
