### ISSUE TITLE
zero-on-free is the worst possible value

### ISSUE THREAD

**Issue by jreiser** [GrapheneOS/hardened_malloc#205]
Setting the bytes in a `free(ptr)` block to zero is the worst possible choice of value because zero masquerades as a common legal value.  There should be an environment variable (checked once only) to specify the value, and if not specified (or an environment variable cannot be used) then the value should be 0x81.  This is the value used fo good advantage for over FIFTY YEARS by https://en.wikipedia.org/wiki/MTS_system_architecture": `New virtual memory pages are initialized to a "core constant" value of x'81' on first reference.`  The value is negative for any integer type, odd (1 mod 2), an unlikely floating-point value, and typically out-of-bounds as a pointer.  All of those properties increase the chance of being detected and/or recognized as an illegal value, which is significant help for increasing the quality of software by detecting bugs earlier.

**Comment by thestinger** [comment]
hardened_malloc is for hardening, not debugging.
