### ISSUE TITLE
fatal allocator error: failed to allocate slab region arm64 rpi

### ISSUE THREAD

**Issue by TheWanderer1983** [GrapheneOS/hardened_malloc#206]
Hello all,
I built the latest harden malloc as per[ these instruction](https://www.kicksecure.com/wiki/Hardened_Malloc/Manual_Installation) on a raspberry pi 4b with latest raspberry pi OS lite 64bit and kernel 5.15.61-v8+ from raspberry pi github.  This system has LKRG built and working.
It builds fine but when i load the library via /etc/ld.so-preload the system completely locks up. Every command to shell comes back with "fatal allocator error: failed to allocate slab region". I need to remove the ld.so-preload and library in order to get the system functional again.

**Comment by thestinger** [comment]
You likely have your kernel configured with a 39-bit address space and the default configuration expects a larger address space. You need to reduce the class region size or change your kernel configuration.

**Comment by TheWanderer1983** [comment]
You were right. I rebuilt the kernel with 48bit and it fixed the problem. Thank you.
