### ISSUE TITLE
RLIMIT_AS

### ISSUE THREAD

**Issue by rusty-snake** [GrapheneOS/hardened_malloc#235]
This more of a question because I want to understand it better than a issue as I think it is intended behaviour.

System: Fedora 39 on x86_64

To prevent programs from taking all your memory causing system freezes until oom-killer kicks in it is often recommended to set RLIMIT_AS¹ to 8GiB (or 2GiB or ...). Doing this with a `echo` like below print "Hello" as expected. However when LD_PRELOADing hardened_malloc it fails.

```console
$ prlimit --as=$(( 8 * 1024 * 1024 * 1024 )) env /bin/echo "Hello"
Hello
$ prlimit --as=$(( 8 * 1024 * 1024 * 1024 )) env LD_PRELOAD=libhardened_malloc.so /bin/echo "Hello"      
fatal allocator error: failed to reserve allocator state
```

As I said I think this is intended behaviour, but this raises the question whether RLIMIT_AS is generally bad for security.

---

¹ cgroups would be better but are more complicated to understand if you don't do it through systemd-run.

**Comment by thestinger** [comment]
You're limiting address space, not memory usage. Reserving terabytes of virtual memory doesn't use more memory than reserving 4k of virtual memory. It's bad practice to use RLIMIT_AS and it's incompatible with the hardening used not just by hardened_malloc but lots of other software including Chromium.
