### ISSUE TITLE
Error during compilation on Whonix

### ISSUE THREAD

**Issue by madaidan** [GrapheneOS/hardened_malloc#81]
Hi,

I get an error when compiling on Whonix 14. I have tried with GCC and Clang and get the same error. It works fine on Arch though.

I am using GCC version 6.3.0 and Clang version 3.8.1-24.

With Clang:
```user@host:~/hardened_malloc$ make CC=clang CXX=clang++
clang -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=137438953472  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o h_malloc.o h_malloc.c
clang: error: unknown argument: '-fno-plt'
<builtin>: recipe for target 'h_malloc.o' failed
make: *** [h_malloc.o] Error 1
user@host:~/hardened_malloc$ 
```

With GCC:
```user@host:~/hardened_malloc$ make
cc -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt -pipe -Wall -Wextra  -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=137438953472  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o h_malloc.o h_malloc.c
h_malloc.c:10:21: fatal error: threads.h: No such file or directory
 #include <threads.h>
                     ^
compilation terminated.
<builtin>: recipe for target 'h_malloc.o' failed
make: *** [h_malloc.o] Error 1
```

Possibly similar to #49 and #61.

**Comment by thestinger** [comment]
The same comment I made there applies:

https://github.com/GrapheneOS/hardened_malloc/issues/61#issuecomment-432180212

> I treat supporting older versions as a porting issue to deal with occasionally. It can be a blocker for tagged releases. I don't really want to think about portability across platforms and older versions of dependencies when I'm trying to get something else finished and landed.

The Clang issue can be resolved by removing the `-fno-plt` switch from the Makefile to work around the fact that you're using such an old version (3.8.0) rather than a recent release (current is 8.0.0).

It's not working for you with GCC because you're trying to use arenas on a platform without the C11 thread API. You can work around that by setting `CONFIG_N_ARENA` to `1` instead of `4`. Since there's a standard API, I used it rather than a compiler extension.

**Comment by thestinger** [comment]
Clang issue should be resolved by https://github.com/GrapheneOS/hardened_malloc/commit/5449f4a94edd86024ec3478e586da692c46f136a.

**Comment by thestinger** [comment]
Resolution for the 2nd part of the issue due to an out-of-date glibc: https://github.com/GrapheneOS/hardened_malloc/commit/12525f28618ef577ea931a1dc151cd19a462aa73.

**Comment by madaidan** [comment]
Thanks! It works flawlessly now.
