### ISSUE TITLE
Support systems without mremap

### ISSUE THREAD

**Issue by lattera** [GrapheneOS/hardened_malloc#96]
HardenedBSD does not contain the `mremap` syscall. hardened_malloc will need to adjust accordingly.

**Comment by thestinger** [comment]
@lattera I actually implemented this in https://github.com/GrapheneOS/hardened_malloc/commit/a32e26b8e9987177ef7573594b2aab2104ca9d3f already as preparation for more portability.

**Comment by thestinger** [comment]
It's also useful on Linux for removing mremap from system call whitelists if reduced attack surface is considered more important than the performance win, especially since it's only used for very large allocations.

**Comment by thestinger** [comment]
It could also be useful on Linux as a configuration option for removing mremap from system call whitelists if reduced attack surface is considered more important than the performance win, especially since it's only used for very large allocations.

**Comment by lattera** [comment]
Awesome! Thanks! I'm just opening tickets based on memory of prior discussions with you. Sorry for any line noise. Just trying to hash out the very beginnings of hardened_malloc's import into HardenedBSD. :)

**Comment by thestinger** [comment]
I'd start with porting it as a standalone library, using the `h_` prefix option, and get it working like that, and then start working on integrating it into libc once the basics are confirmed to work.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/hardened_malloc/blob/master/Android.bp#L14 is how to enable that option.

**Comment by lattera** [comment]
Yup. Exactly what I'm doing.

**Comment by thestinger** [comment]
Also, https://github.com/GrapheneOS/platform_bionic/commit/20160b81611d6f2acd9ab59241bebeac7cf1d71c is where I replace jemalloc in Bionic for 64-bit. For Bionic, I'm building it as a static library outside of libc, as they do for jemalloc, and then it gets surfaced via the libc wrappers. Most libc implementation don't have these kinds of wrappers which Bionic uses for malloc debugging, etc. with great care taken to make the function pointers read-only after early initialization. I don't want it in GrapheneOS, but it would be entirely possible to provide the ability to switch between hardened_malloc and jemalloc at runtime with that infrastructure.
